CREATE DATABASE IF NOT EXISTS robot CHARACTER SET UTF8;
USE robot;

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
	ID INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	USERNAME VARCHAR(64) NOT NULL DEFAULT '',
	PASSWORD VARCHAR(32) NOT NULL DEFAULT '',
	PRIMARY KEY(ID),
	KEY I_SYS_USER_USERNAME (USERNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户表';